export const handleUncaughtExceptionMonitor = (error: Error): void => {
  console.log(`[test] uncaught exception ${error}`)
}
